apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-cert
  namespace: default
spec:
  secretName: default-cert-secret
  dnsNames:
    - MYDOMAIN
  issuerRef:
    name: default-cluster-issuer
    kind: ClusterIssuer
