apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: MYUSER@wcupa.edu
    privateKeySecretRef:
      name: default-cert-secret
    solvers:
      - http01:
          ingress:
            class: traefik
